health_data:
  file_path: "data/mch_kit_data.csv"
  columns:
    date: "dataDate"
    district: "districtName"
    mandal: "mandalName"
    village: "villageName"
    metrics:
      - "pwRegCnt"
      - "kitsCnt"
      - "anc1Cnt"
      - "anc2Cnt"
      - "anc4Cnt"
      - "highRiskCnt"
      - "govtDelCnt"
      - "pvtDelCnt"
      - "chImzCnt"
  metrics_to_calculate:
    - "kit_coverage_ratio"
    - "high_risk_ratio"
    - "anc2_to_anc1_ratio"
    - "anc4_to_anc1_ratio"
  default_thresholds:
    kit_coverage_ratio: 0.8
    high_risk_ratio: 0.1
    anc2_to_anc1_ratio: 0.9
    anc4_to_anc1_ratio: 0.5

temperature_data:
  file_path: "data/temperature_report.csv"
  columns:
    district: "District"
    min_temp: "Min Temp"
    max_temp: "Max Temp (°C)"
  metrics:
    - "avg_temperature"
    - "max_temperature"
    - "min_temperature"

tourism_domestic:
  file_path: "data/Tourism Domestic Visitors Data 2024.csv"
  columns:
    district: "district"
    date: "month"
    visitors: "visitors"
  metrics:
    - "visitors"
  metrics_to_calculate:
    - "total_visitors"
    - "avg_monthly_visitors"
    - "peak_month_visitors"

consumption_details:
  file_path: "data/consumption_details.csv"
  columns:
    circle: "circle"
    division: "division"
    subdivision: "subdivision"
    section: "section"
    area: "area"
    catdesc: "catdesc"
    catcode: "catcode"
    totservices: "totservices"
    billdservices: "billdservices"
    units: "units"
    load: "load"
  display_name: "RTGS - Consumption Details"
  metrics_to_calculate:
    - "totservices"
    - "billdservices"
    - "load"
    - "units"
